name: build

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "bot@github.com"
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python rss.py > docs/main.rss
        git commit docs/main.rss -m "Generated RSS file"
        git push
