name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'codingandsprite/rss'
    - run: |
        git config user.name "github-actions[bot]"
        git config user.email "bot@github.com"
        python3 -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        mkdir -p docs
        touch docs/main.rss
        python rss.py > docs/main.rss
        git add docs/main.rss
        git commit docs/main.rss -m "Generated RSS file"
        git push
